name: Build and Push Pythnet Image
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dispatch_description:
        description: "Dispatch description"
        required: true
        type: string
jobs:
  agent-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@8a84b07f2009032ade05a88a28750d733cc30db1
        with:
          role-to-assume: arn:aws:iam::192824654885:role/github-actions-ecr
          aws-region: eu-west-2
      - uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
        env:
          AWS_REGION: us-east-1
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
      - uses: haya14busa/action-cond@v1
        id: image_tag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref_name }}
          if_false: ${{ github.sha }}
      - uses: mad9000/actions-find-and-replace-string@3
        id: image_tag_formatted # This is to replace the + in the tag with a - as docker doesn't like it
        with:
          source: ${{ steps.image_tag.outputs.value }}
          find: '+'
          replace: '-'
          replaceAll: true
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: public.ecr.aws/pyth-network/pythnet:${{ steps.image_tag_formatted.outputs.value }}
